#!/usr/bin/env bash

set -eu

ORG_PATH="github.com/coreos"
REPO_PATH="${ORG_PATH}/container-linux-config-transpiler"
VERSION=$(git describe --dirty)
GLDFLAGS="-X github.com/coreos/container-linux-config-transpiler/internal/version.Raw=${VERSION}"

if [ ! -h gopath/src/${REPO_PATH} ]; then
	mkdir -p gopath/src/${ORG_PATH}
	ln -s ../../../.. gopath/src/${REPO_PATH} || exit 255
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath

eval $(go env)

echo "Building Config Transpiler..."
go build -ldflags "${GLDFLAGS}" -o ${GOBIN}/ct ${REPO_PATH}/internal
